[[mapping.fundamentals]]
= Spring Data Object Mapping Fundamentals

This section covers the fundamentals of Spring Data object mapping, object creation, field and property access, mutability and immutability.

Core responsibility of the Spring Data object mapping is to create instances of domain objects and map the store-native data structures onto those.
This means we need two fundamental steps:

1. Instance creation by using one of the constructors exposed.
2. Instance population to materialize all exposed properties.

[[mapping.fundamentals.object-creation]]
== Object creation

Spring Data automatically tries to detect a persistent entity's constructor to be used to materialize objects of that type.
The resolution algorithm works as follows:

1. If there is a no-argument constructor, it will be used.
Other constructors will be ignored.
2. If there is a single constructor taking arguments, it will be used.
3. If there are multiple constructors taking arguments, the one to be used by Spring Data will have to be annotated with `@PersistenceConstructor`.

The value resolution assumes constructor argument names to match the property names of the entity,
i.e. the resolution will be performed as if the property was to be populated, including all customizations in mapping (different datastore column or field name etc.).
This also requires either parameter names information available in the class file or an `@ConstructorProperties` annotation being present on the constructor.

[[mapping.fundamentals.object-creation.details]]
.Object creation internals
****

To avoid the overhead of reflection, Spring Data object creation uses a factory class generated at runtime by default,
which will call the domain classes constructor directly.
I.e. for this example type:

[source, java]
----
class Person {
  Person(String firstname, String lastname) { … }
}
----

we will create a factory class semantically equivalent to this one at runtime:

[source, java]
----
class PersonObjectInstantiator implements ObjectInstantiator {

  Object newInstance(Object... args) {
    return new Person((String) args[0], (String) args[1]);
  }
}
----

This gives us a roundabout 10% performance boost over reflection.
For the domain class to be eligible for such optimization, it needs to adhere to a set of constraints:

- it must not be a private class
- it must not be a non-static inner class
- it must not be a CGLib proxy class
- the constructor to be used by Spring Data must not be private

If any of these criteria match, Spring Data will fall back to entity instantiation via reflection.
****

[[mapping.fundamentals.property-population]]
== Property population

Once an instance of the entity has been created, Spring Data populates all remaining persistent properties of that class.
Unless already populated by the entity's constructor (i.e. consumed through its constructor argument list),
the identifier property will be populated first to allow the resolution of cyclic object references.
After that, all non-transient properties that have not already been populated by the constructor are set on the entity instance.
For that we use the following algorithm:

1. If the property is immutable but exposes a _wither_ method (see below), we use the _wither_ to create a new entity instance with the new property value.
2. If property access (i.e. access through getters and setters) is defined, we are invoking the setter method.
3. By default, we set the field value directly.

[[mapping.fundamentals.property-population.details]]
.Property population internals
****
Similarly to our <<mapping.object-creation.details,optimizations in object construction>> we also use
Spring Data runtime generated accessor classes to interact with the entity instance.

[source, java]
----
class Person {

  private final Long id;
  private String firstname;
  private @AccessType(Type.PROPERTY) String lastname;

  Person() {
    this.id = null;
  }

  Person(Long id, String firstname, String lastname) {
    // Field assignments
  }

  Person withId(Long id) {
    return new Person(id, this.firstname, this.lastame);
  }

  void setLastname(String lastname) {
    this.lastname = lastname;
  }
}
----

.A generated Property Accessor
====
[source, java]
----
class PersonPropertyAccessor implements PersistentPropertyAccessor {

  private static final MethodHandle firstname;              <2>

  private Person person;                                    <1>

  public void setProperty(PersistentProperty property, Object value) {

    String name = property.getName();

    if ("firstname".equals(name)) {
      firstname.invoke(person, (String) value);             <2>
    } else if ("id".equals(name)) {
      this.person = person.withId((Long) value);            <3>
    } else if ("lastname".equals(name)) {
      this.person.setLastname((String) value);              <4>
    }
  }
}
----
<.> PropertyAccessor's hold a mutable instance of the underlying object.
    This is, to enable mutations of otherwise immutable properties.
<.> By default, Spring Data uses field-access to read and write property values.
    As per visibility rules of `private` fields, `MethodHandles` are used to interact with fields.
<.> The class exposes a `withId(…)` method that's used to set the identifier,
    e.g. when an instance is inserted into the datastore and an identifier has been generated. Calling `withId(…)` creates a new `Person` object. All subsequent mutations will take place in the new instance leaving the previous untouched.
<.> Using property-access allows direct method invocations without using `MethodHandles`.
====

This gives us a roundabout 25% performance boost over reflection.
For the domain class to be eligible for such optimization, it needs to adhere to a set of constraints:

- Types must not reside in the default or under the `java` package.
- Types and their constructors must be `public`
- Types that are inner classes must be `static`.
- The used Java Runtime must allow for declaring classes in the originating `ClassLoader`.
  Java 9 and newer impose certain limitations.

By default, Spring Data attempts to use generated property accessors and falls back to reflection-based ones if a limitation is detected.
****

Let's have a look at the following entity:

.A sample entity
====
[source, java]
----
class Person {

  private final @Id Long id;                                                <1>
  private final String firstname, lastname;                                 <2>
  private final LocalDate birthday;
  private final int age; <3>

  private String comment;                                                   <4>
  private @AccessType(Type.PROPERTY) String remarks;                        <5>

  static Person of(String firstname, String lastname, LocalDate birthday) { <6>

    return new Person(null, firstname, lastname, birthday,
      Period.between(birthday, LocalDate.now()).getYears());
  }

  Person(Long id, String firstname, String lastname, LocalDate birthday, int age) { <6>

    this.id = id;
    this.firstname = firstname;
    this.lastname = lastname;
    this.birthday = birthday;
    this.age = age;
  }

  Person withId(Long id) {                                                  <1>
    return new Person(id, this.firstname, this.lastname, this.birthday);
  }

  void setRemarks(String remarks) {                                         <5>
    this.remarks = remarks;
  }
}
----
====
<.> The identifier property is final but set to `null` in the constructor.
    The class exposes a `withId(…)` method that's used to set the identifier, e.g. when an instance is inserted into the datastore and an identifier has been generated.
    The original `Person` instance stays unchanged as a new one is created.
    The same pattern is usually applied for other properties that are store managed but might have to be changed for persistence operations.
<.> The `firstname` and `lastname` properties are ordinary immutable properties potentially exposed through getters.
<.> The `age` property is an immutable but derived one from the `birthday` property.
    With the design shown, the database value will trump the defaulting as Spring Data uses the only declared constructor.
    Even if the intent is that the calculation should be preferred, it's important that this constructor also takes `age` as parameter (to potentially ignore it)
    as otherwise the property population step will attempt to set the age field and fail due to it being immutable and no wither being present.
<.> The `comment` property is mutable is populated by setting its field directly.
<.> The `remarks` properties are mutable and populated by setting the `comment` field directly or by invoking the setter method for
<.> The class exposes a factory method and a constructor for object creation.
    The core idea here is to use factory methods instead of additional constructors to avoid the need for constructor disambiguation through `@PersistenceConstructor`.
    Instead, defaulting of properties is handled within the factory method.

== General recommendations

* _Try to stick to immutable objects_ --
  Immutable objects are straightforward to create as materializing an object is then a matter of calling its constructor only.
  Also, this avoids your domain objects to be littered with setter methods that allow client code to manipulate the objects state.
  If you need those, prefer to make them package protected so that they can only be invoked by a limited amount of co-located types.
  Constructor-only materialization is up to 30% faster than properties population.
* _Provide an all-args constructor_ --
  Even if you cannot or don't want to model your entities as immutable values,
  there's still value in providing a constructor that takes all properties of the entity as arguments, including the mutable ones,
  as this allows the object mapping to skip the property population for optimal performance.
* _Use factory methods instead of overloaded constructors to avoid ``@PersistenceConstructor``_ --
  With an all-argument constructor needed for optimal performance, we usually want to expose more application use case specific constructors
  that omit things like auto-generated identifiers etc.
  It's an established pattern to rather use static factory methods to expose these variants of the all-args constructor.
* _Make sure you adhere to the constraints that allow the generated instantiator and property accessor classes to be used_
* _For identifiers to be generated, still use a final field in combination with a wither method_
* _Use Lombok to avoid boilerplate code_ --
  As persistence operations usually require a constructor taking all arguments, their declaration becomes a tedious repetition of boilerplate parameter to field assignments that can best be avoided by using Lombok's `@AllArgsConstructor`.

[[mapping.fundamentals.kotlin]]
== Kotlin support

Spring Data adapts specifics of Kotlin to allow object creation and mutation.

=== Kotlin object creation

Kotlin classes are supported to be instantiated , all classes are immutable by default and require explicit property declarations to define mutable properties.
Consider the following `data` class `Person`:

====
[source,java]
----
data class Person(val id: String, val name: String)
----
====

The class above compiles to a typical class with an explicit constructor.
We can customize this class by adding another constructor and annotate it with `@PersistenceConstructor` to indicate a constructor preference:

====
[source,java]
----
data class Person(var id: String, val name: String) {

    @PersistenceConstructor
    constructor(id: String) : this(id, "unknown")
}
----
====

Kotlin supports parameter optionality by allowing default values to be used if a parameter is not provided.
When Spring Data detects a constructor with parameter defaulting, then it leaves these parameters absent
if the data store does not provide a value (or simply returns `null`) so Kotlin can apply parameter defaulting.
Consider the following class that applies parameter defaulting for `name`

====
[source,java]
----
data class Person(var id: String, val name: String = "unknown")
----
====

Every time the `name` parameter is either not part of the result or its value is `null`, then the `name` defaults to `unknown`.

=== Property population of Kotlin data classes

In Kotlin, all classes are immutable by default and require explicit property declarations to define mutable properties.
Consider the following `data` class `Person`:

====
[source,java]
----
data class Person(val id: String, val name: String)
----
====

This class is effectively immutable.
It allows to create new instances as Kotlin generates a `copy(…)` method that creates new object instances
copying all property values from the existing object and applying property values provided as arguments to the method.


=== Projections

Like https://docs.spring.io/spring-data/neo4j/docs/5.0.0.RELEASE/reference/html/#reference_programming-projections[Spring Neo4j Data], SDN/RX returns domain model usually. In other cases, it might be required to return simplified and reduced view. Given example domain model:

====
[source,java]
----
@Node
public class Cinema {

  private Long id;
  private String name, location;

  @Relationship(type = "VISITED", direction = Relationship.INCOMING)
  private Set<User> visited = new HashSet<>();

  @Relationship(type = "BLOCKBUSTER", direction = Relationship.OUTGOING)
  private Movie blockbusterOfTheWeek;

  ...
}
----
====

repository would look like following:

====
[source,java]
----
public interface CinemaRepository extends Neo4jRepository<Cinema, Long> {

  Cinema findByName(String name);
}
----
====

where `Cinema findByName(String name);` will return the all `Cinema` attributes including values for related models like `visited` and `blockbusterOfTheWeek`.
If related nodes are mapped to domain models that also have some properties annotated with `@Relationship` those will be returned too. Let's say `User` model mentioned in example has relationship to some model `Role`.
Given query would return those roles for each item in `visited` property of `Cinema`.

NOTE: There is a virtual depth limit of 5 to prevent loading too much data when using queries derived from finder-method names. SDN/RX doesn't support customization of this depth.

There are 2 ways to avoid this:

* use a custom annotated query (<<repositories.query-methods.query-creation)
* use a projection

Simple way to use projection is using java interface. For our example domain model we can fetch only `name` and `blockbusterOfTheWeek` properties.

.Simple projection using interface
====
[source,java]
----
public interface CinemaNameAndBlockbuster {
	public String getName();
	public Movie getBlockbusterOfTheWeek();
}
----
====
WARNING: Projections declare a contract between the underlying type, and the method signatures related to the exposed properties. This means it is required to name getter methods according to the property name of the underlying type. If the underlying property is named name, then the getter method must be named getName.

This type of projection is also called closed projection.

Accordingly, repository needs to be changed to return projection instead of domain model:

.Repository returning projection defined with interface
====
[source,java]
----
interface CinemaRepository extends Neo4jRepository<Cinema, Long> { // <1>

  CinemaNameAndBlockbuster findByName(String name); // <2>
}
----
<.> Repository mapped to specific domain model
<.> Method returns projection defined as interface instead of domain model.
====
Given repository will fetch only attributes required by projection interface from data.

WARNING: Combining custom queries using `@Query` and projections is not supported out of the box. Instead, you need to change `RETURN` part of custom cypher query to comply with expected projection model.

==== Remodeling data

Sometimes you need different names for properties. You can achieve this using `@Value` annotation with SpEL.
Using this approach you can also get sub-properties of nested models.

.Advanced projection
====
[source,java]
----
interface RenamedProperty {

  @Value("#{target.name}") // <1>
  String getCinemaName();

  @Value("#{target.blockbusterOfTheWeek.name}") // <2>
  String getBlockbusterOfTheWeekName();
}
----
<.> Expose `name` of model Cinema as `cinemaName`
<.> Expose sub-property `name` of linked `Model` entity referenced as property `blockbusterOfTheWeekName` in `Cinema`
====
TIP: Property name is prefixed with target which is the variable name pointing to the backing object.

==== Limitations

Having getter *methods* to achieve projections prevents having other methods inside interface. This means that interfaces you already have in your code might not be supported.
Let's say you have
```java
interface I {
    String getName();
    default String sayHello() {
        return "Hello " + getName();
    }
}
class A implements I {
    private String name;
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
}
class B implements I {
    public String getName() { return "This Class can only get name"; }
}
```
Interface *I* is not suitable for projection as accessing that method would throw exception message "Invoked method is not a property accessor!"
There's no special support for Kotlin in this case, so it has the same drawbacks.